In [18]:
import numpy as np
from pprint import pprint

In [39]:
# Example
x = np.array([[5, 3, 7], 
              [2, 4, 1]])
y = np.array([[100, 10, 1]]).T

try:
    w = np.linalg.inv(x) * y
    pprint(w)
except:
    pass

try:    
    w2 = (x.T * y) / (x.T * x)
    pprint(w2)
except:
    pass

In [46]:
# A
x = np.array([[2]])
y = np.array([8])
w = np.linalg.inv(x) * y

try:
    w = np.linalg.inv(x) * y
    pprint(w)
except:
    pass

try:    
    w2 = (x.T * y) / (x.T * x)
    pprint(w2)
except:
    pass

array([[ 4.]])
array([[ 4.]])


In [49]:
# B
x = np.array([[0]])
y = np.array([[8]])
w = np.linalg.inv(x) * y

try:
    w = np.linalg.inv(x) * y
    pprint(w)
except:
    pass

try:    
    w2 = (x.T * y) / (x.T * x)
    pprint(w2)
except:
    pass

LinAlgError: Singular matrix

In [50]:
# C
x = np.array([[2, 4]])
y = np.array([[8]])
w = np.linalg.solve(x, y)

try:
    w = np.linalg.inv(x) * y
    pprint(w)
except:
    pass

try:    
    w2 = (x.T * y) / (x.T * x)
    pprint(w2)
except:
    pass

LinAlgError: Last 2 dimensions of the array must be square

In [51]:
# D
x = np.array([[2, 4,], 
              [0, 1]])
y = np.array([8, 3]).T
w = np.linalg.inv(x) * y

try:
    w = np.linalg.inv(x) * y
    pprint(w)
except:
    pass

try:    
    w2 = (x.T * y) / (x.T * x)
    pprint(w2)
except:
    pass

array([[ 4., -6.],
       [ 0.,  3.]])
array([[  4.,  nan],
       [ inf,   3.]])


/home/cneiderer/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:14: RuntimeWarning: divide by zero encountered in true_divide
  
/home/cneiderer/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:14: RuntimeWarning: invalid value encountered in true_divide
  


In [9]:
# E
x = np.array([[2, 4],
              [0, 1],
              [9, 5]])
y = np.array([8, 
              3, 
              1])
w = np.linalg.inv(x) * y
w2 = x.T * y / x.T * x

LinAlgError: Last 2 dimensions of the array must be square

In [12]:
# F
x = np.array([[2, 2],
              [3, 3]])
y = np.array([4, 
              6])
w = np.linalg.inv(x) * y
w
w2 = x.T * y / x.T * x
q

array([[ -3.60287970e+16,   3.60287970e+16],
       [  3.60287970e+16,  -3.60287970e+16]])

array([[  8.,  12.],
       [ 12.,  18.]])